test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -78,6 +78,7 @@ jobs:
           echo "DYNAMIC_VARIABLE_PATH=$dynamic_variable_path" >> $GITHUB_ENV
           echo "TEST_CASE_COMMAND=$test_case_command" >> $GITHUB_ENV
           echo "REQUIREMENTS_FILE=$requirements_file" >> $GITHUB_ENV
+          echo "TEST_CASE_METHOD=$test_case_method" >> $GITHUB_ENV
       
           # Debug logs
           echo "Constructed TEST_CASE_COMMAND: $test_case_command"
@@ -86,10 +87,12 @@ jobs:
 
       - name: Install Dependencies
         run: |
-          if [[ "$TEST_CASE_METHOD" == "ec2_al2" || "$TEST_CASE_METHOD" == "ec2_win" ]]; then
-            pip install -r ec2_requirements.txt
+          if [[ -f "$REQUIREMENTS_FILE" ]]; then
+            echo "Installing dependencies from $REQUIREMENTS_FILE..."
+            pip install -r "$REQUIREMENTS_FILE"
           else
-            pip install -r api_requirements.txt
+            echo "Requirements file not found: $REQUIREMENTS_FILE"
+            exit 1
           fi
 
       - name: Trigger Testing Framework
